version: '2.2'

services:
    confident-confinement:
        build: service
        restart: on-failure
        ports:
            - 17172:31337
        privileged: true
        stop_grace_period: 3s
        mem_limit: 1G
        memswap_limit: 1G
        cpu_count: 1
        pids_limit: 2048
        ulimits: 
            nofile:
                soft: 8192
                hard: 8192
